#!/usr/bin/env python3
"""Generate GRAPH_REPORT.md from graph.json — replaces the stale graphify-CLI
report that hardcoded "100% EXTRACTED". Always run after merge.py / make-2d.py /
make-3d.py / name-communities.py so the report matches the live artifacts.

Per audit `tasks/full-system-audit-2026-05-12/graph-integrity.md`:
- Finding #2: always regenerate alongside graph.json
- Finding #3: exclude singleton communities from headline count
- Finding #7: surface real edge confidence tag distribution

Run: `python3 make-report.py`
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from datetime import datetime, timezone
from collections import Counter

# Per spec-graphify-out-relocation-2026-05-16.md — pipeline outputs in brain repo.
_BRAIN = os.environ.get("CORE_BRAIN")
if not _BRAIN:
    print(f"{Path(__file__).name}: $CORE_BRAIN not set — required.", file=sys.stderr)
    sys.exit(1)
OUT = Path(_BRAIN) / "_build" / "output" / "graphify-out"
OUT.mkdir(parents=True, exist_ok=True)
GRAPH = OUT / "graph.json"
NAMES = OUT / "community-names.json"
REPORT = OUT / "GRAPH_REPORT.md"


def main():
    g = json.loads(GRAPH.read_text())
    nodes = g.get("nodes", [])
    edges = g.get("edges", [])
    meta = g.get("metadata", {})

    # Community sizes (exclude singletons from "real communities" count)
    com_sizes: Counter[int] = Counter()
    for n in nodes:
        cid = n.get("community")
        if cid is not None and cid != -1:
            com_sizes[cid] += 1
    total_communities = len(com_sizes)
    singleton_communities = sum(1 for size in com_sizes.values() if size == 1)
    real_communities = total_communities - singleton_communities

    # Edge confidence distribution (audit #7)
    edge_conf: Counter[str] = Counter()
    for e in edges:
        c = e.get("properties", {}).get("confidence")
        if c is None:
            edge_conf["NONE"] += 1
        else:
            edge_conf[c] += 1

    # Node type distribution
    node_types: Counter[str] = Counter()
    for n in nodes:
        node_types[n.get("type", "unknown")] += 1

    # Isolated count (already in metadata if merge.py wrote it)
    node_ids_with_edges: set[str] = set()
    for e in edges:
        node_ids_with_edges.add(e.get("source"))
        node_ids_with_edges.add(e.get("target"))
    isolated = sum(1 for n in nodes if n.get("id") not in node_ids_with_edges)

    # Named communities count
    named_communities = 0
    if NAMES.exists():
        names = json.loads(NAMES.read_text())
        named_communities = len(names)

    # Compose report
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total_edges = len(edges)
    total_nodes = len(nodes)

    def pct(n, d):
        return f"{100*n/d:.1f}%" if d else "—"

    lines = [
        f"# Graph Report — Core Brain ({generated})",
        "",
        "## Summary",
        f"- **{total_nodes:,} nodes** · **{total_edges:,} edges** · **{real_communities:,} communities** (excluding {singleton_communities} singletons; {total_communities} total Louvain partitions)",
        f"- **{isolated:,} isolated nodes** ({pct(isolated, total_nodes)}) — connected to nothing else in the graph",
        f"- Named communities: {named_communities} / {total_communities} ({pct(named_communities, total_communities)})",
        "",
        "## Edge confidence distribution",
        "| Tag | Count | Share |",
        "|---|---|---|",
    ]
    for tag in ("EXTRACTED", "INFERRED", "AMBIGUOUS", "NONE"):
        count = edge_conf.get(tag, 0)
        lines.append(f"| {tag} | {count:,} | {pct(count, total_edges)} |")

    lines += [
        "",
        "## Node type distribution",
        "| Type | Count | Share |",
        "|---|---|---|",
    ]
    for t, count in sorted(node_types.items(), key=lambda x: -x[1]):
        lines.append(f"| {t} | {count:,} | {pct(count, total_nodes)} |")

    lines += [
        "",
        "## Top-20 communities by size",
        "| Rank | Community ID | Size | Name |",
        "|---|---|---|---|",
    ]
    names_map = json.loads(NAMES.read_text()) if NAMES.exists() else {}
    for rank, (cid, size) in enumerate(com_sizes.most_common(20), start=1):
        name = names_map.get(str(cid), f"(unnamed Community {cid})")
        lines.append(f"| {rank} | {cid} | {size:,} | {name} |")

    lines += [
        "",
        "## Source",
        f"- Graph: `graph.json` ({GRAPH.stat().st_size:,} bytes)",
        f"- Generated by: `scheduling/graphify-brain/make-report.py`",
        f"- Generated at: {generated}",
        "",
    ]

    REPORT.write_text("\n".join(lines))
    print(f"Wrote {REPORT} ({REPORT.stat().st_size:,} bytes)")
    print(f"  {total_nodes:,} nodes · {total_edges:,} edges · {real_communities:,} real communities · {isolated:,} isolated")


if __name__ == "__main__":
    main()
